# Generated by Django 5.2.4 on 2026-07-21 19:25

import apps.news.models
import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.news.models.news_cover_upload_path, validators=[common.validators.validate_image_size, common.validators.validate_image_content, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر شاخص'),
        ),
    ]
