from django.test import TestCase
from django.urls import reverse

from .models import Employee, WorkGroup


class WorkGroupModelTests(TestCase):
    def test_slug_autogenerated_from_persian_name(self):
        group = WorkGroup.objects.create(name="کارگروه فناوری اطلاعات")
        self.assertTrue(group.slug)

    def test_slug_unique_on_collision(self):
        WorkGroup.objects.create(name="پژوهش")
        second = WorkGroup.objects.create(name="پژوهش")
        self.assertNotEqual(WorkGroup.objects.first().slug, second.slug)


class WorkGroupListViewTests(TestCase):
    def test_list_page_status_code(self):
        response = self.client.get(reverse("workgroups:list"))
        self.assertEqual(response.status_code, 200)

    def test_list_page_shows_groups(self):
        WorkGroup.objects.create(name="منابع انسانی")
        response = self.client.get(reverse("workgroups:list"))
        self.assertContains(response, "منابع انسانی")


class WorkGroupDetailViewTests(TestCase):
    def setUp(self):
        self.group = WorkGroup.objects.create(
            name="فناوری اطلاعات", description="توسعه و پشتیبانی سامانه‌ها"
        )
        self.employee = Employee.objects.create(
            workgroup=self.group,
            full_name="علی رضایی",
            position="توسعه‌دهنده بک‌اند",
        )

    def test_detail_page_status_code(self):
        response = self.client.get(
            reverse("workgroups:detail", kwargs={"slug": self.group.slug})
        )
        self.assertEqual(response.status_code, 200)

    def test_detail_page_shows_employees(self):
        response = self.client.get(
            reverse("workgroups:detail", kwargs={"slug": self.group.slug})
        )
        self.assertContains(response, "علی رضایی")
        self.assertContains(response, "توسعه‌دهنده بک‌اند")

    def test_detail_page_handles_group_with_no_employees(self):
        empty_group = WorkGroup.objects.create(name="گروه خالی")
        response = self.client.get(
            reverse("workgroups:detail", kwargs={"slug": empty_group.slug})
        )
        self.assertEqual(response.status_code, 200)


class WorkGroupsHeaderDropdownTests(TestCase):
    def test_dropdown_appears_on_unrelated_pages(self):
        # The dropdown is injected by a context processor, so it must
        # show up even on a page that has nothing to do with workgroups.
        WorkGroup.objects.create(name="حقوقی")
        response = self.client.get(reverse("home:index"))
        self.assertContains(response, "حقوقی")
