# Generated by Django 5.2.4 on 2026-07-24 08:00

import apps.training.models
import common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='در صورت خالی بودن به\u200cصورت خودکار از نام ساخته می\u200cشود.', unique=True, verbose_name='نامک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی آموزشی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای آموزشی',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='در صورت خالی بودن به\u200cصورت خودکار از عنوان ساخته می\u200cشود.', max_length=220, unique=True, verbose_name='نامک')),
                ('summary', models.CharField(max_length=300, verbose_name='خلاصه')),
                ('description', models.TextField(verbose_name='توضیحات کامل دوره')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.training.models.course_cover_upload_path, validators=[common.validators.validate_image_size, common.validators.validate_image_content, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر شاخص')),
                ('level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح دوره')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='مدت دوره (ساعت)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.coursecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': 'دوره\u200cهای آموزشی',
                'ordering': ['-published_at', '-id'],
                'get_latest_by': 'published_at',
                'indexes': [models.Index(fields=['status', '-published_at'], name='training_status_pubdate_idx')],
            },
        ),
    ]
