from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from .models import News, NewsStatus

User = get_user_model()


class NewsListTests(TestCase):
    def setUp(self):
        for i in range(15):
            News.objects.create(
                title=f"خبر شماره {i}",
                summary="خلاصه",
                body="متن",
                status=NewsStatus.PUBLISHED,
                published_at=timezone.now(),
            )

    def test_list_page_status_code(self):
        response = self.client.get(reverse("news:list"))
        self.assertEqual(response.status_code, 200)

    def test_list_page_is_paginated(self):
        response = self.client.get(reverse("news:list"))
        self.assertTrue(response.context["is_paginated"])
        self.assertEqual(len(response.context["news_list"]), 12)

    def test_list_page_second_page(self):
        response = self.client.get(reverse("news:list") + "?page=2")
        self.assertEqual(len(response.context["news_list"]), 3)

    def test_list_page_hides_drafts(self):
        News.objects.create(
            title="پیش‌نویس مخفی",
            summary="خلاصه",
            body="متن",
            status=NewsStatus.DRAFT,
        )
        response = self.client.get(reverse("news:list"))
        self.assertNotContains(response, "پیش‌نویس مخفی")


class NewsDetailTests(TestCase):
    def setUp(self):
        self.author = User.objects.create_user(username="editor", password="test-pass-123")
        self.published = News.objects.create(
            title="خبر منتشرشده",
            author=self.author,
            summary="خلاصه",
            body="متن کامل",
            status=NewsStatus.PUBLISHED,
            published_at=timezone.now(),
        )
        self.draft = News.objects.create(
            title="خبر پیش‌نویس",
            summary="خلاصه",
            body="متن کامل",
            status=NewsStatus.DRAFT,
        )

    def test_published_news_detail_accessible(self):
        response = self.client.get(
            reverse("news:detail", kwargs={"slug": self.published.slug})
        )
        self.assertEqual(response.status_code, 200)

    def test_draft_news_detail_returns_404(self):
        response = self.client.get(
            reverse("news:detail", kwargs={"slug": self.draft.slug})
        )
        self.assertEqual(response.status_code, 404)

    def test_slug_autogenerated_from_title(self):
        self.assertTrue(self.published.slug)

    def test_view_count_increments_on_detail_view(self):
        self.assertEqual(self.published.views, 0)
        self.client.get(reverse("news:detail", kwargs={"slug": self.published.slug}))
        self.published.refresh_from_db()
        self.assertEqual(self.published.views, 1)

    def test_author_not_required(self):
        orphan = News.objects.create(
            title="خبر بدون نویسنده",
            summary="خلاصه",
            body="متن",
            status=NewsStatus.PUBLISHED,
            published_at=timezone.now(),
        )
        self.assertIsNone(orphan.author)

    def test_get_absolute_url_points_to_news_app(self):
        self.assertEqual(
            self.published.get_absolute_url(),
            reverse("news:detail", kwargs={"slug": self.published.slug}),
        )
