# Generated by Django 5.2.4 on 2026-07-19 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import apps.home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(
                        help_text="یک مسیر داخلی (مثلاً /news/) یا یک آدرس کامل معتبر.",
                        max_length=300,
                        verbose_name="آدرس",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="باز شدن در تب جدید"
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم منوی هدر",
                "verbose_name_plural": "منوی هدر",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(
                        help_text="یک مسیر داخلی (مثلاً /news/) یا یک آدرس کامل معتبر.",
                        max_length=300,
                        verbose_name="آدرس",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "لینک سریع فوتر",
                "verbose_name_plural": "لینک\u200cهای سریع فوتر",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(
                        help_text="یک مسیر داخلی (مثلاً /news/) یا یک آدرس کامل معتبر.",
                        max_length=300,
                        verbose_name="آدرس",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً یک کلاس آیکون Bootstrap Icons، مانند bi-people",
                        max_length=100,
                        verbose_name="کلاس آیکون",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیح کوتاه"
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک بخش شرکت",
                "verbose_name_plural": "لینک\u200cهای بخش\u200cهای شرکت",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="درباره ایران خودرو",
                        max_length=150,
                        verbose_name="عنوان درباره ما",
                    ),
                ),
                ("about_text", models.TextField(verbose_name="متن درباره ما")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        validators=[
                            apps.home.models.validate_image_size,
                            apps.home.models.validate_image_content,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="تلفن"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="آدرس"),
                ),
            ],
            options={
                "verbose_name": "اطلاعات سایت",
                "verbose_name_plural": "اطلاعات سایت",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="در صورت خالی بودن به\u200cصورت خودکار از عنوان ساخته می\u200cشود.",
                        max_length=220,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("summary", models.CharField(max_length=300, verbose_name="خلاصه")),
                ("body", models.TextField(verbose_name="متن کامل")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.home.models.news_cover_upload_path,
                        validators=[
                            apps.home.models.validate_image_size,
                            apps.home.models.validate_image_content,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
                "ordering": ["-published_at", "-id"],
                "get_latest_by": "published_at",
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="news_status_pubdate_idx",
                    )
                ],
            },
        ),
    ]
