# Generated by Django 5.2.4 on 2026-07-22 06:27

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_move_news_to_news_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(
                        upload_to="announcements/",
                        validators=[
                            common.validators.validate_image_size,
                            common.validators.validate_image_content,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                        verbose_name="تصویر اعلان",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "اطلاعیه",
                "verbose_name_plural": "اطلاعیه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
