from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from .models import News, NewsStatus, SectionLink, SiteInfo


class HomePageTests(TestCase):
    def setUp(self):
        SiteInfo.objects.create(about_text="متن آزمایشی درباره ما")
        SectionLink.objects.create(title="منابع انسانی", url="/hr/", order=1)
        News.objects.create(
            title="خبر آزمایشی",
            summary="خلاصه خبر آزمایشی",
            body="متن کامل خبر آزمایشی",
            status=NewsStatus.PUBLISHED,
            published_at=timezone.now(),
        )

    def test_home_page_status_code(self):
        response = self.client.get(reverse("home:index"))
        self.assertEqual(response.status_code, 200)

    def test_home_page_shows_published_news(self):
        response = self.client.get(reverse("home:index"))
        self.assertContains(response, "خبر آزمایشی")

    def test_home_page_hides_unpublished_news(self):
        News.objects.create(
            title="خبر منتشرنشده",
            summary="خلاصه",
            body="متن",
            status=NewsStatus.DRAFT
        )
        response = self.client.get(reverse("home:index"))
        self.assertNotContains(response, "خبر منتشرنشده")

    def test_home_page_shows_section_links(self):
        response = self.client.get(reverse("home:index"))
        self.assertContains(response, "منابع انسانی")


class NewsDetailTests(TestCase):
    def setUp(self):
        SiteInfo.objects.create(about_text="متن آزمایشی")
        self.published = News.objects.create(
            title="خبر منتشرشده",
            summary="خلاصه",
            body="متن کامل",
            status=NewsStatus.PUBLISHED,
            published_at=timezone.now(),
        )
        self.draft = News.objects.create(
            title="خبر پیش‌نویس",
            summary="خلاصه",
            body="متن کامل",
            status=NewsStatus.DRAFT
        )

    def test_published_news_detail_accessible(self):
        response = self.client.get(
            reverse("home:news-detail", kwargs={"slug": self.published.slug})
        )
        self.assertEqual(response.status_code, 200)

    def test_draft_news_detail_returns_404(self):
        response = self.client.get(
            reverse("home:news-detail", kwargs={"slug": self.draft.slug})
        )
        self.assertEqual(response.status_code, 404)

    def test_slug_autogenerated_from_title(self):
        self.assertTrue(self.published.slug)
