from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from .models import Course, CourseCategory, CourseStatus

User = get_user_model()


class CourseListTests(TestCase):
    def setUp(self):
        self.safety = CourseCategory.objects.create(name="ایمنی و بهداشت")
        self.technical = CourseCategory.objects.create(name="مهارت‌های فنی")
        for i in range(15):
            Course.objects.create(
                title=f"دوره شماره {i}",
                category=self.safety,
                summary="خلاصه",
                description="توضیحات",
                status=CourseStatus.PUBLISHED,
                published_at=timezone.now(),
            )
        Course.objects.create(
            title="دوره فنی نمونه",
            category=self.technical,
            summary="خلاصه ویژه فنی",
            description="توضیحات",
            status=CourseStatus.PUBLISHED,
            published_at=timezone.now(),
        )

    def test_list_page_status_code(self):
        response = self.client.get(reverse("training:list"))
        self.assertEqual(response.status_code, 200)

    def test_list_page_is_paginated(self):
        response = self.client.get(reverse("training:list"))
        self.assertTrue(response.context["is_paginated"])
        self.assertEqual(len(response.context["courses"]), 12)

    def test_list_page_filters_by_category(self):
        response = self.client.get(
            reverse("training:list"), {"category": self.technical.slug}
        )
        self.assertContains(response, "دوره فنی نمونه")
        self.assertNotContains(response, "دوره شماره 0")

    def test_list_page_search_by_title(self):
        response = self.client.get(reverse("training:list"), {"q": "فنی نمونه"})
        self.assertContains(response, "دوره فنی نمونه")
        self.assertNotContains(response, "دوره شماره 0")

    def test_list_page_hides_drafts(self):
        Course.objects.create(
            title="دوره پیش‌نویس مخفی",
            summary="خلاصه",
            description="توضیحات",
            status=CourseStatus.DRAFT,
        )
        response = self.client.get(reverse("training:list"))
        self.assertNotContains(response, "دوره پیش‌نویس مخفی")


class CourseDetailTests(TestCase):
    def setUp(self):
        self.instructor = User.objects.create_user(
            username="trainer", password="test-pass-123"
        )
        self.published = Course.objects.create(
            title="دوره منتشرشده",
            instructor=self.instructor,
            summary="خلاصه",
            description="توضیحات کامل",
            status=CourseStatus.PUBLISHED,
            published_at=timezone.now(),
        )
        self.draft = Course.objects.create(
            title="دوره پیش‌نویس",
            summary="خلاصه",
            description="توضیحات",
            status=CourseStatus.DRAFT,
        )

    def test_published_course_detail_accessible(self):
        response = self.client.get(
            reverse("training:detail", kwargs={"slug": self.published.slug})
        )
        self.assertEqual(response.status_code, 200)

    def test_draft_course_detail_returns_404(self):
        response = self.client.get(
            reverse("training:detail", kwargs={"slug": self.draft.slug})
        )
        self.assertEqual(response.status_code, 404)

    def test_slug_autogenerated_from_title(self):
        self.assertTrue(self.published.slug)

    def test_view_count_increments_on_detail_view(self):
        self.assertEqual(self.published.views, 0)
        self.client.get(reverse("training:detail", kwargs={"slug": self.published.slug}))
        self.published.refresh_from_db()
        self.assertEqual(self.published.views, 1)

    def test_instructor_not_required(self):
        orphan = Course.objects.create(
            title="دوره بدون مدرس",
            summary="خلاصه",
            description="توضیحات",
            status=CourseStatus.PUBLISHED,
            published_at=timezone.now(),
        )
        self.assertIsNone(orphan.instructor)


class CourseCategoryModelTests(TestCase):
    def test_slug_autogenerated_from_persian_name(self):
        category = CourseCategory.objects.create(name="مدیریت پروژه")
        self.assertTrue(category.slug)

    def test_slug_unique_on_collision(self):
        CourseCategory.objects.create(name="ایمنی")
        second = CourseCategory.objects.create(name="ایمنی")
        self.assertNotEqual(CourseCategory.objects.first().slug, second.slug)
