# Generated by Django 5.2.4 on 2026-07-21 19:25

import apps.workgroups.models
import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'کارگروه', 'verbose_name_plural': 'کارگروه\u200cها'},
        ),
        migrations.AddField(
            model_name='workgroup',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کارگروه'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='در صورت خالی بودن به\u200cصورت خودکار از نام ساخته می\u200cشود.', unique=True, verbose_name='نامک'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='سمت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.workgroups.models.employee_photo_upload_path, validators=[common.validators.validate_image_size, common.validators.validate_image_content, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='عکس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن داخلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('workgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='workgroups.workgroup', verbose_name='کارگروه')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
