# Generated by Django 5.2.4 on 2026-07-24 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0002_alter_workgroup_options_workgroup_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='در صورت اتصال، این کارمند می\u200cتواند وارد پورتال شده و جلسات پیش رو خود را ببیند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری'),
        ),
    ]
