# Generated by Django 5.2.4 on 2026-07-23 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workgroups', '0002_alter_workgroup_options_workgroup_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام اتاق')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل استقرار')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت (نفر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اتاق جلسه',
                'verbose_name_plural': 'اتاق\u200cهای جلسه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('agenda', models.TextField(blank=True, verbose_name='دستور جلسه')),
                ('date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='لغو شده')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال دعوت\u200cنامه')),
                ('send_error', models.CharField(blank=True, max_length=500, verbose_name='خطای ارسال')),
                ('cancellation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال اطلاعیه لغو')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to='workgroups.employee', verbose_name='کارمند')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='meetings.meeting', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه جلسه',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cهای جلسه',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='meetings.MeetingInvitation', to='workgroups.employee', verbose_name='شرکت\u200cکنندگان'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(help_text='اتاق\u200cهای دارای جلسه را نمی\u200cتوان حذف کرد؛ در عوض غیرفعال کنید.', on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.meetingroom', verbose_name='اتاق'),
        ),
        migrations.AddConstraint(
            model_name='meetinginvitation',
            constraint=models.UniqueConstraint(fields=('meeting', 'employee'), name='unique_meeting_employee'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['room', 'date'], name='meeting_room_date_idx'),
        ),
    ]
